name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew make makePluginsJson
        
      - name: Switch to builds branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git checkout builds || git checkout -b builds
          git pull origin builds || true
          
      - name: Copy built plugins
        run: |
          cp *Provider/*.cs3 ./ || true
          cp build/plugins.json ./ || true
          
      - name: Commit and push changes
        run: |
          git add *.cs3 plugins.json || true
          git commit -m "Build ${{ github.sha }}" || true
          git push -f origin builds 